[package]
name = "hello"
version = "0.1.0"
authors = ["rich-murphey <rich@murphey.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.5.1"
rmp-serde = "0.14.3"
serde = { version = "1.0.114", features = ["derive"] }
wasm-bindgen = "0.2.63"
wee_alloc = "0.4.5"
